### ISSUE TITLE
appearance bug

### ISSUE THREAD

**Issue by ghost** [ncyxie/Notepad-Dot#2]
if you set dark mode and than follow tools or set it per color mode (same color as the font) the text vanishes because "same color as background" - you can reset it by simply setting dark / light mode only again (or just setting the font color).

Settings multiple appearance settings, yes I got why but I think it's a bit irritating. 

tyvm for the application! and please keep what youre doing ~ learning

**Comment by ghost** [comment]
have something small to add
a button has no specific name
(show tools) the second button -> (hover) toolStripButon26

**Comment by ncyxie** [comment]
> 
> 
> if you set dark mode and than follow tools or set it per color mode (same color as the font) the text vanishes because "same color as background" - you can reset it by simply setting dark / light mode only again (or just setting the font color).
> 
> Settings multiple appearance settings, yes I got why but I think it's a bit irritating.
> 
> tyvm for the application! and please keep what youre doing ~ learning

If I understood your question correctly, I think this is completely normal, and if user would face this issue, he would change text font color/textbox color manually. Some users might even want to have same textbox and text font color for certain reasons. Application has ability to remember and write user changed settings into config, so in my opinion, everything is fine.

**Comment by ncyxie** [comment]
> 
> 
> have something small to add
> a button has no specific name
> (show tools) the second button -> (hover) toolStripButon26

I see, thanks for letting know those minor bugs, haven't noticed that bug myself until now.
