### ISSUE TITLE
enhancement request

### ISSUE THREAD

**Issue by ghost** [ncyxie/Notepad-Dot#3]
is there a feature like left/right padding? I don't like it if its pressed against a border
does your app gets features like one word bold / one italic? I dont know how its called but may you get what I mean

**Comment by ncyxie** [comment]
> is there a feature like left/right padding? I don't like it if its pressed against a border

No, not yet. I might look forward to implement this function in the future.

> does your app gets features like one word bold / one italic? I dont know how its called but may you get what I mean

I tried to implement this, and I did, but application wasn't able to save multiple font styles, so I didn't include it to stable releases. I might try to implement it again, but I hesitate if I will be able to do it.

**Comment by ghost** [comment]
aright thanks, take your time to make the right decisions and do not hesitate to try things again!
If you want this Feature in than do it! 

or make an Plugin Menu (in the future) where you can put in plugins like Text Highlights / Bold, Italic Formats etc, so you have a "simple hackable lightweight" notepad <- was my idea.. but I can't code I suck at programming.
- may some user gonna make some stuff for it later :p 

I mean Notepad++ has something like this but I don't like the code highlighting and already implemented features.. and even the themeing.. yours is not advanced as ++ but I like your still a even more, keep it up.

**Comment by ncyxie** [comment]
Thank you for your advices/ideas, will see what I can do and what not. Feel free to create a new issue if you will find some bugs and/or you want to give me some fresh feature ideas. I appreciate your contribution into my project.
